### ISSUE TITLE
Download the converted weights for intialization from here

### ISSUE THREAD

**Issue by cuihuitao** [amanjhunjhunwala/PSPNet-Tensorflow#1]
I don,t download the converted weights for intialization from here. @amanjhunjhunwala

**Comment by amanjhunjhunwala** [comment]
The link works well. Could you try these : 

https://www.dropbox.com/sh/vyseh2mixm6pjih/AACvHZAnTGC36hnOOs3Zybdva?dl=0

OR

https://drive.google.com/open?id=0Bxc6HbrmToSVNUp5R3oweTd3NWs
